apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../manager-base

images:
- name: controller
  newName: quay.io/yshnaidm/amd-gpu-operator
  newTag: check-different-namespace
- name: worker
  newName: quay.io/edge-infrastructure/kernel-module-management-worker
  newTag: latest

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

generatorOptions:
  disableNameSuffixHash: true
