apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

patches:
- path: manager_auth_proxy_patch.yaml
- path: manager_config_patch.yaml

images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: registry.redhat.io/openshift4/ose-kube-rbac-proxy
  newTag: v4.13

configurations:
- kustomizeconfig.yaml
