---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpue.openshift.io
  resources:
  - gpuenablements
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpue.openshift.io
  resources:
  - gpuenablements/finalizers
  verbs:
  - update
- apiGroups:
  - kmm.sigs.x-k8s.io
  resources:
  - modules
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmm.sigs.x-k8s.io
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
