apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: openshift-amd-gpu
    repository: https://github.com/yevgeny-shnaidman/amd-gpu-operator
  name: amd-gpu-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DeviceConfig describes how to enable AMD GPU device
      displayName: DeviceConfig
      kind: DeviceConfig
      name: deviceconfigs.amd.io
      version: v1alpha1
  description: AMD GPU operator
  displayName: amd-gpu-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - amd-gpu-operator
  links:
  - name: Amd Gpu Operator
    url: https://amd-gpu-operator.domain
  maturity: alpha
  provider:
    name: amd-gpu-operator
  version: 0.0.0
